CREATE DATABASE EJERCICIO_9
USE EJERCICIO_9

CREATE TABLE  Persona(
	TipoDoc char(30) NOT NULL, 
	NroDoc INT NOT NULL,
	Nombre CHAR(30),
	Dirección CHAR(30) NOT NULL,
	FechaNac DATE NOT NULL,
	Sexo CHAR(20) NOT NULL,
	CONSTRAINT PK_PERSONA PRIMARY KEY (TipoDoc,NroDoc),
	CONSTRAINT UQ_TIPODOC UNIQUE(TipoDoc),
	CONSTRAINT UQ_NRODOC UNIQUE(NroDoc),
);
CREATE TABLE Progenitor  (
	TipoDoc CHAR(30) NOT NULL, 
	NroDoc INT NOT NULL, 
	TipoDocHijo CHAR(30) NOT NULL, 
	NroDocHijo INT NOT NULL,
	CONSTRAINT PK_PROGENITOR PRIMARY KEY(TipoDoc,NroDoc,TipoDocHijo,NroDocHijo),
	
	CONSTRAINT FK_PROGENITOR_TIPODOC FOREIGN KEY (TipoDoc) REFERENCES Persona(TipoDoc),
	CONSTRAINT FK_PROGENITOR_NRODOC FOREIGN KEY (NroDoc) REFERENCES Persona(NroDoc),
	CONSTRAINT FK_PROGENITOR_TIPODOC_HIJO FOREIGN KEY (TipoDoc) REFERENCES Persona(TipoDoc),
	CONSTRAINT FK_PROGENITOR_NRODOC_HIJO FOREIGN KEY (NroDoc) REFERENCES Persona(NroDoc)
);