CREATE DATABASE EJERCICIO_4
USE EJERCICIO_4
GO
CREATE TABLE Persona (
	dni INT PRIMARY KEY NOT NULL, 
	nomPersona CHAR(30), 
	telefono INT NOT NULL,
	CONSTRAINT FK_PERSONA FOREIGN KEY (dni) REFERENCES Persona(dni)
);
CREATE TABLE Empresa (
	nomEmpresa CHAR(30) PRIMARY KEY NOT NULL, 
	telefono INT NOT NULL,
	CONSTRAINT FK_EMPRESA FOREIGN KEY (nomEmpresa) REFERENCES Empresa (nomEmpresa)

);
CREATE TABLE Vive (
	dni INT PRIMARY KEY NOT NULL, 
	calle CHAR(30) NOT NULL, 
	ciudad CHAR(30) NOT NULL
	CONSTRAINT FK_VIVE FOREIGN KEY (dni) REFERENCES Vive (dni)
);
CREATE TABLE Trabaja (
	dni INT PRIMARY KEY NOT NULL, 
	nomEmpresa CHAR(30) NOT NULL, 
	salario DECIMAL (6,2) NOT NULL, 
	feIngreso DATE NOT NULL, 
	feEgreso DATE NOT NULL,
	CONSTRAINT FK_TRABAJA_PERSONA FOREIGN KEY (dni) REFERENCES Persona (dni),
	CONSTRAINT FK_TRABAJA_EMPRESA FOREIGN KEY (nomEmpresa) REFERENCES Empresa (nomEmpresa)

);
CREATE TABLE Situada_En (
	nomEmpresa CHAR(30) PRIMARY KEY NOT NULL, 
	ciudad CHAR(30) NOT NULL,
	CONSTRAINT FK_SITUADA_EN FOREIGN KEY (nomEmpresa) REFERENCES Empresa (nomEmpresa)
);
CREATE TABLE Supervisa (
	dniPer INT  NOT NULL, 
	dniSup INT NOT NULL,
	CONSTRAINT PK_SUPERVISA PRIMARY KEY (dniPer,dniSup),
	CONSTRAINT FK_SUPERVISOR FOREIGN KEY (dniSup) REFERENCES Persona(dni),
	CONSTRAINT FK_SUPERVISA_PERSONA FOREIGN KEY (dniPer) REFERENCES Persona(dni)
);