CREATE DATABASE EJERCICIO_6

USE EJERCICIO_6

CREATE TABLE Vuelo (
	NroVuelo INT NOT NULL, 
	Desde CHAR(30) NOT NULL,
	Hasta CHAR(30) NOT NULL,
	Fecha DATE NOT NULL,
	CONSTRAINT PK_VUELO PRIMARY KEY (NroVuelo,Desde),
	CONSTRAINT UQ_VUELO_NROVUELO UNIQUE (NroVuelo)
);
CREATE TABLE Avion_utilizado (
	NroVuelo INT PRIMARY KEY NOT NULL, 
	TipoAvion CHAR (30) NOT NULL, 
	NroAvion INT NOT NULL
);
CREATE TABLE Info_Pasajeros(
	NroVuelo INT NOT NULL,
	Documento INT NOT NULL,
	Nombre CHAR(30),
	Origen CHAR(30),
	Destino CHAR(30),
	CONSTRAINT PK_INFORMACION PRIMARY KEY (NroVuelo,Documento),
	CONSTRAINT FK_INFORMACION_VUELO FOREIGN KEY (NroVuelo) REFERENCES  Vuelo(NroVuelo) 
);