CREATE DATABASE EJERCICIO_10
USE EJERCICIO_10

CREATE TABLE Metodo (
    ID INT PRIMARY KEY NOT NULL,
    Clase VARCHAR(50) NOT NULL,
    Metodo VARCHAR(50) NOT NULL
);
CREATE TABLE Ambiente (
    ID INT PRIMARY KEY NOT NULL,
    Descripcion VARCHAR(100) NOT NULL
);

-- Tabla Page
CREATE TABLE Pages (
    ID VARCHAR(15) PRIMARY KEY NOT NULL,
    WebPage VARCHAR(100) NOT NULL,
    IDAmbiente INT NOT NULL,
    CONSTRAINT FK_PAGE_AMBIENTE FOREIGN KEY (IDAmbiente) REFERENCES Ambiente(ID)
);

-- Tabla Request
CREATE TABLE Request (
    NoRequest INT PRIMARY KEY NOT NULL,
    ID VARCHAR(15) NOT NULL,
    Fecha DATE NOT NULL,
    Hora TIME NOT NULL,
    IDMetodo INT NOT NULL,
    CONSTRAINT FK_REQUEST_METODO FOREIGN KEY (IDMetodo) REFERENCES Metodo(ID),
    CONSTRAINT FK_REQUEST_PAGE FOREIGN KEY (ID) REFERENCES Pages(ID)
);
