CREATE DATABASE EJERCICIO_5
USE EJERCICIO_5
GO

CREATE TABLE Rubro (
	CodRubro INT PRIMARY KEY NOT NULL, 
	NombRubro CHAR(30) NOT NULL
);
CREATE TABLE Cliente (
	CodCli INT PRIMARY KEY NOT NULL, 
	Nombre CHAR(30), 
	Apellido CHAR(30), 
	Dirección CHAR(30) NOT NULL, 
	Tel INT NOT NULL, 
	Email CHAR(60) NOT NULL
);
CREATE TABLE Pelicula (
	CodPel INT PRIMARY KEY NOT NULL, 
	Titulo CHAR(30), 
	Duracion DECIMAL(2,2), 
	Año DATE NOT NULL, 
	CodRubro INT NOT NULL,
	CONSTRAINT FK_PELICULA FOREIGN KEY(CodRubro) REFERENCES Rubro(CodRubro)
);
CREATE TABLE Ejemplar (
	CodEj INT NOT NULL, 
	CodPel INT NOT NULL, 
	Estado CHAR(20), 
	Ubicación CHAR(30),
	CONSTRAINT PK_EJEMPLAR PRIMARY KEY (CodEj,CodPel),
	CONSTRAINT UQ_EJEMPLAR_CODEJ UNIQUE (CodEj)
);
CREATE TABLE Prestamo (
	CodPrest INT PRIMARY KEY NOT NULL, 
	CodEj INT NOT NULL, 
	CodPel INT NOT NULL, 
	CodCli INT NOT NULL, 
	FechaPrest DATE NOT NULL,
	FechaDev DATE NOT NULL,
	CONSTRAINT FK_PRESTAMO_EJEMPLAR FOREIGN KEY(CodEj) REFERENCES Ejemplar(CodEj),
	CONSTRAINT FK_PRESTAMO_PELICULA FOREIGN KEY(CodPel) REFERENCES Pelicula(CodPel),
	CONSTRAINT FK_PRESTAMO_CLIENTE FOREIGN KEY(CodCli) REFERENCES Cliente(CodCli),

);