CREATE DATABASE EJERCICIO_8
USE EJERCICIO_8

CREATE TABLE Persona(
	dni INT PRIMARY KEY NOT NULL,
	nombre CHAR(30) NOT NULL
);
CREATE TABLE Bar(
	CodBar INT PRIMARY KEY NOT NULL,
	nombre CHAR(30) NOT NULL
);
CREATE TABLE Cerveza(
	codCer INT PRIMARY KEY NOT NULL,
	nombre char(30) NOT NULL
);
CREATE TABLE Frecuenta(
	persona INT NOT NULL,
	bar INT NOT NULL,
	CONSTRAINT PK_FRECUENCIA PRIMARY KEY(persona,bar), 
	CONSTRAINT FK_FRECUENCIA_PERSONA FOREIGN KEY (persona) REFERENCES Persona(dni),
	CONSTRAINT FK_FRECUENCIA_BAR FOREIGN KEY (bar) REFERENCES Bar(CodBar)

);
CREATE TABLE Sirve(
	bar INT NOT NULL,
	cerveza INT NOT NULL,
	CONSTRAINT PK_SIRVE PRIMARY KEY(bar,cerveza),
	CONSTRAINT FK_SIRVE_BAR FOREIGN KEY (bar) REFERENCES Bar(CodBar),
	CONSTRAINT FK_SIRVE_CERVEZA FOREIGN KEY (cerveza) REFERENCES Cerveza(codCer)
);
CREATE TABLE Gusta(
	persona INT NOT NULL,
	cerveza INT NOT NULL
	CONSTRAINT PK_GUSTA PRIMARY KEY(persona,cerveza),
	CONSTRAINT FK_GUSTA_PERSONA FOREIGN KEY (persona) REFERENCES Persona(dni),
	CONSTRAINT FK_GUSTA_CERVEZA FOREIGN KEY (cerveza) REFERENCES Cerveza(codCer)
);
