create DATABASE Facturacion 
use  Facturacion
go

CREATE TABLE Proveedor(
	NroProv INT PRIMARY KEY NOT NULL,
	NomProv CHAR(30) NOT NULL,
	Categoria CHAR(50) NOT NULL,
	CiudadProv CHAR(40) NOT NULL
);
CREATE TABLE Articulo(
	NroArt INT PRIMARY KEY NOT NULL,
	Descripcion CHAR(60) NOT NULL,
	CiudadArt CHAR(30) NOT NULL,
	Precio DECIMAL (9,2) NOT NULL
);
CREATE TABLE Cliente(
	NroCli INT PRIMARY KEY NOT NULL,
	NomCli CHAR(30) NOT NULL,
	CiudadCli CHAR(30) NOT NULL
);
CREATE TABLE Pedido(
	NroPed INT PRIMARY KEY NOT NULL,
	NroArt INT NOT NULL,
	NroCli INT NOT NULL,
	NroProv INT NOT NULL,
	FechaPedido DATE NOT NULL,
	Cantidad INT NOT NULL,
	PrecioTotal DECIMAL(6,2),
	CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (NroPed) REFERENCES Cliente(NroCli),
	CONSTRAINT FK_PEDIDOS_ARTICULO FOREIGN KEY (NroArt) REFERENCES Articulo(NroArt),
	CONSTRAINT FK_PEDIDOS_PROVEEDOR FOREIGN KEY (NroProv) REFERENCES Proveedor(NroProv)
);
CREATE TABLE Stock(
	NroArt INT NOT NULL,
	Fecha DATE NOT NULL,
	Cantidad INT NOT NULL,
	CONSTRAINT PKSTOCK PRIMARY KEY (NroArt,Fecha),
	CONSTRAINT FK_STOCK_ART FOREIGN KEY(NroArt) REFERENCES Articulo(NroArt) 
);